// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewZealand_Courier.Data;

namespace NewZealand_Courier.Migrations
{
    [DbContext(typeof(NewZealand_CourierContext))]
    [Migration("20210811215603_ddda")]
    partial class ddda
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NewZealand_Courier.Models.CourierDeliver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeliveryPerson_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryPerson_Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryPerson_EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryPerson_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CourierDeliver");
                });

            modelBuilder.Entity("NewZealand_Courier.Models.CourierOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CourierOffice");
                });

            modelBuilder.Entity("NewZealand_Courier.Models.CourierReceiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Barcode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Receiver_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver_Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CourierReceiver");
                });

            modelBuilder.Entity("NewZealand_Courier.Models.Vehicles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourierDeliverId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryPerson_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vehicle_Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vehicle_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vehicle_Redgo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourierDeliverId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("NewZealand_Courier.Models.Vehicles", b =>
                {
                    b.HasOne("NewZealand_Courier.Models.CourierDeliver", "CourierDeliver")
                        .WithMany()
                        .HasForeignKey("CourierDeliverId");
                });
#pragma warning restore 612, 618
        }
    }
}
